### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by facuquilmes123** [soumyadityac/youtube-viewer#4]
Noy working for me.
result with: docker-compose build and npm run build

![yt](https://user-images.githubusercontent.com/63804749/80925903-f6ce0200-8d69-11ea-938f-f11acb2febf4.JPG)

![yt2](https://user-images.githubusercontent.com/63804749/80925915-09483b80-8d6a-11ea-81bc-54e017c6a6f5.JPG)

Thanks a lot.

**Comment by soumyadityac** [comment]
Could be an issue with `docker-compose`. What is the version of docker and docker-compose you're using? Could you also share the windows version?

**Comment by h4ckm3-id** [comment]
decrease your scale,,
i try on vps linux with 2 cpu, 4gb ram,, the limit is ytview=6, if i set =7,, it will crash,

**Comment by facuquilmes123** [comment]
> `docker-compose`. What is the version of docker and docker-compose you're using?

![git](https://user-images.githubusercontent.com/63804749/81747427-7b153900-947e-11ea-844b-c8e8bcb19b7d.JPG)


and docker

```
$ docker-compose -v
docker-compose version 1.24.1, build 4667896b
```



Thanks a lot for your time and work !!!
Congratulations Bro.

**Comment by pavel191919191** [comment]
I have purchased working bot from here http://dbtechlabs.com/youtube-view-bot.html if it helps you.
dont send too much I am able only like 12 or 15 per 1 video per day but still better then nothing

**Comment by faizshir** [comment]
Running the repo on windows and I am getting this error while trying to build the app


Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version
  File "site-packages\docker\utils\decorators.py", line 46, in inner
  File "site-packages\docker\api\client.py", line 228, in _get
  File "site-packages\requests\sessions.py", line 543, in get
  File "site-packages\requests\sessions.py", line 530, in request
  File "site-packages\requests\sessions.py", line 643, in send
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 677, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 392, in _make_request
  File "http\client.py", line 1244, in request
  File "http\client.py", line 1290, in _send_request
  File "http\client.py", line 1239, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 966, in send
  File "site-packages\docker\transport\npipeconn.py", line 32, in connect
  File "site-packages\docker\transport\npipesocket.py", line 23, in wrapped
  File "site-packages\docker\transport\npipesocket.py", line 72, in connect
  File "site-packages\docker\transport\npipesocket.py", line 59, in connect
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose\cli\main.py", line 67, in main
  File "compose\cli\main.py", line 123, in perform_command
  File "compose\cli\command.py", line 69, in project_from_options
  File "compose\cli\command.py", line 132, in get_project
  File "compose\cli\docker_client.py", line 43, in get_client
  File "compose\cli\docker_client.py", line 170, in docker_client
  File "site-packages\docker\api\client.py", line 188, in __init__
  File "site-packages\docker\api\client.py", line 213, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find t
le specified.')
[5696] Failed to execute script docker-compose
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! youtube-viewer@1.0.0 build: `docker-compose build --no-cache`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the youtube-viewer@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sheen\AppData\Roaming\npm-cache\_logs\2020-12-11T09_44_01_232Z-debug.log

C:\youtube-viewer-0.1.1>docker-compose -v
docker-compose version 1.27.4, build 40524192

**Comment by Math-O5** [comment]
@faizshir I had the same issue, bro. The docker engine is running? 

To check: `systemctl status docker`

To active: `systemctl start docker`

Then execute the instructions again with super user.

**Comment by aadhikeshavareddy** [comment]
I have a alternative which is work pretty well....dm on my Instagram
(@adhitechie)
I'll sell it for less price👍😉
